name: Update HPC conferences and locations

on:
  workflow_run:
    workflows: ["Update scraping"]
    types: [completed]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    name: Discover HPC and scrape locations
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install dependencies
      run: |
        python3 -m pip install -r ./requirements.txt
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

    - name: Discover HPC conferences
      run: |
        python3 ./discover_hpc.py --years 2026 2027 | cat

    - name: Scrape conference locations
      run: |
        python3 ./scrape_locations.py | cat

    - name: Push to GitHub
      run: |
        git add hpc_extra.json locations.json
        git diff --cached --quiet || git commit -m "Update HPC and locations $(date --rfc-3339=date)"
        git push
